### PR TITLE
Example combigrid adaptation

### PR DESCRIPTION
**Pull request by freifrauvonbleifrei**
I added a usage example for the adaptive combination grid in C++. 

I would have liked it to also work in python, but apparently SWIG just hates [`unique_ptr`s,](https://github.com/swig/swig/issues/692) and I could not get that to work. It may be worth considering to remove them from the `AdaptiveCombinationGridGenerator` interface.

### CODE REVIEW

**Comment by MichaelReh** [comment]
Swig does not support unique_ptr, only shared_ptr, See [swig.org - Doc](http://www.swig.org/Doc3.0/CPlusPlus11.html) at 7.3.5. It would however, be extremely helpful to have a Python example too.
Would it be painful to drop the unique_ptr here? Otherwise there seem to be hacks, which can make it work, but I don't know if they actually work. We'd have to try. See, e.g. [stackoverflow how-to-handle-unique-ptrs-with-swig](https://stackoverflow.com/questions/27693812/how-to-handle-unique-ptrs-with-swig)

**Comment by freifrauvonbleifrei** [comment]
Hrm, the unique_ptrs are used to allow for dynamic polymorphism, e.g. of different `PriorityEstimator`s, when they are passed to the `AdaptiveCombinationGridGenerator` class.

I was thinking about alternatives, but so far I could not come up with something that would be either templates (which we are trying to avoid for the sake of non-C++-expert usability), other [weird stuff that would be confusing in the future, because it already is now](https://www.boost.org/doc/libs/1_57_0/doc/html/variant.html), or passing raw pointers, which would be really inviting for memory leaks.

@MichaelReh @leiterrl @G-071 since you did that C++ course, maybe you have useful opinions?

**Comment by freifrauvonbleifrei** [comment]
I guess I would go for replacing `unique_ptr`s with `shared_ptr`s since the `AdaptiveCombinationGridGenerator`should not be called very often, and it would be easily reversible once SWIG supports `unique_ptr`s.

**Comment by valentjn** [comment]
@freifrauvonbleifrei A few years ago, we had exact the same question. We looked at the options, and I think the outcome for the SG<sup>++</sup> project was "use `std::unique_ptr` internally, but don't use it in any interfaces" due to SWIG. And SWIG hasn't improved in this regard, unfortunately.

When I was writing the combigrid module, I tried to follow that rule of thumb. Whenever there's a `unique_ptr` on the interface, there's also a plain pointer overload. Just grep for `unique_ptr` in combigrid, e.g., https://github.com/SGpp/SGpp/blob/master/combigrid/src/sgpp/combigrid/basis/HeterogeneousBasis.hpp.

Why not do the same for `AdaptiveCombinationGridGenerator`? You don't need smart pointers for polymorphism. In fact, plain pointers probably even enable polymorphism in Python (inheriting from C++ classes in Python) via SWIG's director feature.

**Comment by freifrauvonbleifrei** [comment]
@valentjn that is a neat idea -- but how do you handle the ownership issue? I would assume the `unique_ptr` variant does transfer ownership, while the plain pointer doesn't. How do you then make sure the object is destroyed exactly once? 

In https://github.com/SGpp/SGpp/blob/master/combigrid/src/sgpp/combigrid/basis/HeterogeneousBasis.hpp it looks like ownership of `bases1d` is not actually transferred, as the assignment happens in the raw pointers, AFAICT. The comment makes it seem that the `base::Basis<level_t, index_t>` objects still need to be destroyed outside the `HeterogeneousBasis`.

I would prefer to transfer ownership here (and as long as this seems hard, go for shared ownership).

**Comment by valentjn** [comment]
@freifrauvonbleifrei On the issue of ownership, the consensus was that whenever there is a plain pointer on the interface, e.g., as returned by the factory functions, users have to take care of that. In the example of `AdaptiveCombinationGridGenerator`, whatever type of pointer you choose, you always have to call `new` in user code before the call. So the user already has to worry about ownership before that. `shared_ptr` would add little benefit here, but rather break consistency to the existing patterns in the module, if you choose to use it just here. Plus, I'm not sure how well `shared_ptr` works with all the fancy SWIG features such as directors.

You don't even need pointers at all, references would work as well in this example, I think.

**Comment by freifrauvonbleifrei** [comment]
??
The whole idea about using smart pointers is to not have the user worry so much about ownership any more -- if something is wrapped in `make_shared` at creation, we can be sure it is deallocated exactly once (as long as there are no raw pointers being passed around and stored, which they are in the current design of the module; or maybe I just don't see the point of the `unique_ptr` variant in that interface yet).

> You don't even need pointers at all, references would work as well in this example, I think.

how would that work? I don't see it.

> I'm not sure how well shared_ptr works with all the fancy SWIG features such as directors.

not sure either, but since there does seem to be support for `shared_ptr`s, I think it would be worth a try to see if its enough so I can get the C++ example to run in Python.

**Comment by freifrauvonbleifrei** [comment]
A quick test reveals: no matter what type of pointer I use (unique, shared, plain), there is something in https://github.com/SGpp/SGpp/blob/master/combigrid/src/sgpp/combigrid/adaptive/AdaptiveCombinationGridGenerator.hpp that makes SWIG segfault whenever I try to include it. 

I don't know enough about SWIG to pinpoint what it is... should I be wrapping vectors and maps manually?

**Comment by valentjn** [comment]
@freifrauvonbleifrei If it’s on the %include line during the SWIG call, you can probably just manually bisect this by deleting half of the members of the header and seeing if it still works, as that step should not depend on the source file.

**Comment by freifrauvonbleifrei** [comment]
so, I finally got a working Python example, yay! The C++ interface is using `shared_ptr`s now. The Python interface is not as simple as i had hoped though. 

@MichaelReh what do you think? do you get what is going on in https://github.com/SGpp/SGpp/blob/exampleCombigridAdaptation/combigrid/examples/combigrid_adaptive.py and https://github.com/SGpp/SGpp/blob/exampleCombigridAdaptation/combigrid/examples/combigrid_adaptive.cpp ?

**Comment by MichaelReh** [comment]
Yes, looks good to me. Very comprehensive example.

**Comment by freifrauvonbleifrei** [comment]
For me, it can be merged once the tests have completed. I would like to add some visualization soon, but that is going to be a separate PR :)

**Review by MichaelReh — APPROVED** [review]

**Pull request merged**
