### PR TITLE
Restore pipeline examples

### PR DESCRIPTION
**Pull request by krsgpp**
The examples of the datamining pipeline are not meant to run without parameters to the config files.

Thus, they will be excluded from the automatic run of examples.

### CODE REVIEW

**Comment by valentjn** [comment]
How is it ensured that the excluded examples actually run such that situations like #99 or #100 are avoided?

**Comment by krsgpp** [comment]
The examples in the pipeline need a valid configuration file as parameter. This config specifies all arguments, such as the dataset file.
There are no dataset path's hard coded in any cpp examples of the datamining pipeline, nor are paths to config files hardcoded.
Of course, if the config file is invalid, the example will fail. Instructions on how the config file is supposed to look can be found here: https://github.com/SGpp/SGpp/wiki/Datadriven-datamining-pipeline-configuration

As for the comment in #103 
> Vital application code, as opposed to showcase examples, should be stored separately (e.g., external repos).

We agreed on July 30 in the discussion round between Dirk, Gregor, Paul and me that the future goal of the datadriven-module will be to be split and also, if reasonable, put into an external repo. However, we also agreed to do this step be step and by responsibility of the maintainers of the specific code.

**Comment by valentjn** [comment]
Yes. Coming back to my question, I understand that for now, we do not care about whether or not the code in that folder actually runs without erroring out?

**Comment by krsgpp** [comment]
Yes, I care about whether or not the code runs. But "runs" means that it is called with arguments (filepaths), and that those files contain meaningful configurations.

**Pull request merged**
