### PR TITLE
Fix some open issues

### PR DESCRIPTION
**Pull request by spc90**
These 2 commits should fix two bugs referenced in #64  and #4 , respectively.

As the fixes were quite easy to make and can be easily checked, I expect the review process to be quick and painless :smile:

### CODE REVIEW

**Comment by spc90** [comment]
@valentjn First things first: the relevant change is removing the debugging code in lines 19-27. That's it :smile: 

Secondly, I was just looking into those style changes, as I don't understand them myself... Even though I have set Eclipse to use the clang-formatter and the provide cpplint, is always finds files in which to correct the line lengths, and it is indeed annoying, not just for reviewing pull requests like now, but also for me to have to revert files to HEAD revision just because of this when I haven't really changed anything in them. 

I had to recently remove the Eclipse .project folder and start anew, so that might be it. But I think in the last project setup I simply unchecked on purpose the "running everything on save" thing precisely because of this...

**Comment by spc90** [comment]
@valentjn ok, so it seems that my formatter was overwriting the 100 characters rule... Sorry about that. I will push a new version without all these annoying style changes :+1:

**Comment by valentjn** [comment]
@spc90 Did you follow the instructions here, esp. those at the bottom of the Style paragraph? http://sgpp.sparsegrids.org/development.html#development_coding_style

**Comment by spc90** [comment]
@valentjn Of course I used the instructions there, but the behavior is still not as I expect. Eclipse has its own internal code formatter (`Window -> Preferences -> C/C++ -> Code Style -> Formatter`) which sets many different things, like bracket styling, using tabs or spaces, size of the tabs and indentation etc.. There are no instructions for that, are there? And now, as a specific example you can test, in `GridPrinter.cpp` on lines 71 and 117 I get cpplint error `Extra space before ( in function call` because a space is introduced after the line is broken, even though Eclipse's internal formatter explicitly does not do that... 

So, from my point of view there is still a problem with how we do the formatting in Eclipse, or some instructions to make it proper are lacking.

**Comment by spc90** [comment]
Unless something else happens, I think the only choice remaining is to NOT run the formatter at all at save and rely on scons to double check everything... and still some indentations will change and the review process will be slow and annoying. Any alternatives are welcomed :smile:

**Comment by spc90** [comment]
@valentjn This is the cleanest the diff can ever be. Because the changes were minor anyway, I've literally redone everything from scratch and used the formatter settings you provided :smile: And also merged the newest changes from `master`. Still, the diff is huge and it's definitely not my fault now :smile: So I will leave this topic to avoid polluting this thread more than it has already been. I will open a separate issue about it, because I still thing this is something we should address. I don't want to code without an IDE :grimacing: 

To finally put this PR to rest: the second change was done in `GridPrinter.cpp` in the functions `printSparseGrid` and `printSparseGridExpTransform`. Everything else are styling changes (mainly indentations), so can be ignored.

**Comment by valentjn** [comment]
@spc90 Ok. Maybe we have different notions of "clean" :wink: I force-pushed what I meant, could you have a look if everything's in there?

**Comment by spc90** [comment]
@valentjn Sure, I could have done what you did by editing maybe with vim or notepad. Here's what I did instead: I took the original file from master into the branch, unmodified, opened it into Eclipse, removed/changed only those particular lines of code, and hit save. And the diff looked as it looked. So please tell me how else am I supposed to work to make it "cleaner"? 

By the way, currently the file is not obeying the Google Style Guide because the original file on master did not obey that style to begin with, or at least the style was not consistent (see e.g. comment lines 97-107, where alignment is bad), so do we even impose that anymore or not? Because cpplint did not complain about neither my, nor your version of these files. So that means there is a lot of leeway in terms of messing up spacing and thus creating weird diffs without any automated checker complaining. And this will keep happening unless we enforce the same style formatting for every code contributor, because I can't stop the IDE from applying the formatting at saving time...

Ok, my rant is over :grin: the changes look as they should, so the branch can be merged :+1:

**Comment by valentjn** [comment]
> the changes look as they should, so the branch can be merged

That's the info I was looking for :wink:

**Pull request merged**
