### PR TITLE
Dima l2 refine

### PR DESCRIPTION
**Pull request by db-Dramos**
Adds support for ModLinear gridType for datadriven OnOff learning.

+ refactores L2 Products in pde, for Linear and ModLinear (optional generalized parameters)
+ adapts OrthoAdapt and Chol cases to automatically handle supported GridTypes when refining

Examples in datadriven/examplesPipeline were tested, and boost tests also didn't return errors.

### CODE REVIEW

**Comment by krsgpp** [comment]
[Jenkins Jobs for this PR](https://simsgs.informatik.uni-stuttgart.de/jenkins/job/SGpp-meta-testing/37/)

**Comment by krsgpp** [comment]
Some of the jenkins Jobs hung up, but others have [warnings to fix](https://simsgs.informatik.uni-stuttgart.de/jenkins/job/SGpp-style-testing/33/warnings14Result/) ([more warnings](https://simsgs.informatik.uni-stuttgart.de/jenkins/job/SGpp-gcc-testing/40/warnings23Result/new/)
As soon fixes for those are commited, I will run jenkins again and hopefully it will run smooth this time :-)

**Comment by db-Dramos** [comment]
> Some of the jenkins Jobs hung up, but others have [warnings to fix](https://simsgs.informatik.uni-stuttgart.de/jenkins/job/SGpp-style-testing/33/warnings14Result/) ([more warnings](https://simsgs.informatik.uni-stuttgart.de/jenkins/job/SGpp-gcc-testing/40/warnings23Result/new/)
> As soon fixes for those are commited, I will run jenkins again and hopefully it will run smooth this time :-)

I fixed the warnings, let's hope that were the only ones :D

**Comment by krsgpp** [comment]
Ok, [next round of Jenkins](https://simsgs.informatik.uni-stuttgart.de/jenkins/job/SGpp-meta-testing/40/) is now running...

**Pull request merged**
