### PR TITLE
Fix missing include for std::hash

### PR DESCRIPTION
**Pull request by jschueller**
Fixes build with clang

### CODE REVIEW

**Comment by jschueller** [comment]
what about my other patches here ?

**Comment by jschueller** [comment]
Why cannot it be tested on the fly on some ci like travis ?

**Comment by leiterrl** [comment]
This is simply how our setup works. A simple Travis run is done first to catch some obvious problems. Then a full run of 11 different configurations using our internal Jenkins build system has to be started manually.

I agree that this a little bit annoying for small pull requests like this one.

**Comment by jschueller** [comment]
you could use circleci, it is supporting conditional workflows like this

**Comment by valentjn** [comment]
Travis can do that as well if you pay. We are a small academic group, not some large software company/open-source foundation with dedicated resources (staff/money) for merging PRs or some expensive non-free CI. Please bear with us, every PR will be reviewed eventually. That being said, the right place to discuss anything not directly related to this PR, such as general CI suggestions, would be opening a new issue.

**Comment by jschueller** [comment]
no no, circleci is free too

**Comment by pfluegdk** [comment]
Thanks for trying to help! 
We had a look at circle-ci in the past, and decided that we could not afford their billed plans. I have to admit that I was not aware of their free plan for open source projects with more resources. 
However, to ensure code quality, we are running a lot of tests, ranging from code coverage to compilation on different platforms. And that would also take quite a bit of time with circle-ci. Furthermore, the local computational resources of our jenkins ci go beyond what is offered in circle-ci's free plan.

**Comment by pfluegdk** [comment]
Addendum: sorry, I mixed that up. The bottleneck is travis, not jenkins, as we can run the many additional local tests with a higher number of threads in parallel. But if I am not wrong, switching to circle-ci would not help.

**Pull request merged**
