### PR TITLE
Add combigrid adaptation level manager

### PR DESCRIPTION
**Pull request by freifrauvonbleifrei**
have dimensional adaptivity in combigrid module

### CODE REVIEW

**Comment by valentjn** [comment]
Could you please split the commits into style- and non-style related ones? Kinda hard to see what's going on.

**Comment by valentjn** [comment]
* `AveragingPriorityEstimator::estimatePriority` doesn't use its `levelVector` argument, intended?
* `AveragingPriorityEstimator` and `WeightedRelevanceCalculator` depend on number of grid points per level. Do they make sense for other grid rules? If yes, I would refactor the occurrences of `<<` etc.

**Comment by freifrauvonbleifrei** [comment]
>     * `AveragingPriorityEstimator::estimatePriority` doesn't use its `levelVector` argument, intended?

yes, there may be other priority estimators that do, e.g. Michael had one that was called `AveragingLevelManager` in the old combigrid.

>     * `AveragingPriorityEstimator` and `WeightedRelevanceCalculator` depend on number of grid points per level. Do they make sense for other grid rules? If yes, I would refactor the occurrences of `<<` etc.

That is a good point!

Another thing that is not entirely clear to me is how results that are not simply added up, such as variance, would fit nicely into the interface.

Quoting @MichaelReh on the old combigrid:
> Insbesondere wird beim AveragingLevelManager mit FullGridSummationStrategyType::VARIANCE als Priorität berechnet, wie hoch der geschätze Einfluss des neuen Levels pro neuem Punkt auf die Varianz ist.

**Comment by freifrauvonbleifrei** [comment]
@valentjn is my idea of "leave it up to others to implement other level occupancies or load models if needed" OK here?

as for the other question, the old combigrid apparently solved it like this:
https://github.com/SGpp/SGpp/blob/87cd3ab7eb9779a827396b536a677707faf69487/combigrid/src/sgpp/combigrid/operation/multidim/fullgrid/FullGridQuadraticSummationStrategy.hpp

should we have another argument similar to a `SummationStrategy` for the `AdaptiveCombinationGridGenerator` which defaults to linear summation as in the current case? Or does it get too fuzzy again already?

**Comment by freifrauvonbleifrei** [comment]
so finally I added a summation function parameter of type `std::function<double(double, double)>` which defaults to `std::plus`. I hope this is still OK-understandable for students, as it allows to implement adaptation criteria quite tidily.

**Pull request merged**
