### PR TITLE
Fix paths and missing datasets in datadriven examples

### PR DESCRIPTION
**Pull request by spc90**
Should fix errors in datadriven examples (@krsgpp see #99 )

### CODE REVIEW

**Comment by valentjn** [comment]
Travis tests begin as soon as the draft status is lifted, although these changes won't have any impact on them. Maybe we should execute the examples somewhere automatically...

**Comment by spc90** [comment]
I think running all examples should be run additionally somewhere, because usually when adding new functionality we also add examples, but testing them manually is not great... and also when changing things most people don't check if that breaks any of the examples either.

**Comment by spc90** [comment]
@krsgpp you're job's not quite done, as not everything is fixed :smile: Some datasets are missing and have to be (re)created, and all datadriven (C++, because the python ones work) examples have to be checked for the right paths (maybe I missed some). Only when all examples run we can merge :wink:

**Comment by krsgpp** [comment]
> @krsgpp you're job's not quite done, as not everything is fixed  Some datasets are missing and have to be (re)created, and all datadriven (C++, because the python ones work) examples have to be checked for the right paths (maybe I missed some). Only when all examples run we can merge

Ok. So we are not going to recreate the missing datasets because they are too big for github (or at least, we would run into the 1GB transfer volume per month problem too soon, which is why I deleted them in the first place).
What we can do is modify the examples so that they use different (smaller) datasets.

**Comment by spc90** [comment]
I think the idea of the examples was always to be easy and show the functionality, so having small test datasets makes sense as the way to fix this :+1:

**Comment by valentjn** [comment]
This has been merged to #103.

**Pull request closed without merging**
