### PR TITLE
remove hardcoded "sgpp/" folder from library install path

### LINKED ISSUE #129: installation layout
sgpp does not install as I'd expected:
- the Python bindings folder pysgpp does not get installed into PREFIX (\$PREFIX/lib/pythonx.y/site-packages/pysgpp on unix or \$PREFIX/Lib/site-packages on win32)
- c++ libs are installed in a \$PREFIX/lib/sggp subfolder (and cannot be loaded by default)

### PR DESCRIPTION
**Pull request by leiterrl**
This fixes #129 and makes life easier when using packaging software.

### CODE REVIEW

**Comment by spc90** [comment]
This doesn't seem to add too much headache to me in the process of making the DM pipeline split work, so I'm fine with it :) 
@leiterrl So basically the new location of the .so files in directly in the lib/ folder, not in lib/sgpp/, right? This seems to be it...

**Comment by leiterrl** [comment]
> This doesn't seem to add too much headache to me in the process of making the DM pipeline split work, so I'm fine with it :)
> @leiterrl So basically the new location of the .so files in directly in the lib/ folder, not in lib/sgpp/, right? This seems to be it...

Yes that's basically it. This seems to be the expected behavior by other people/software. Also it makes sense to not have hardcoded paths in your build process. The old behavior can always be replicated by setting the appropriate build variables.

**Comment by valentjn** [comment]
I think this misses a few occurrences. I recommend grepping for lib.*sgpp (case-insensitive) to find most of them.

**Comment by valentjn** [comment]
Of course, this also holds for the Wiki repo.

**Comment by leiterrl** [comment]
> I think this misses a few occurrences. I recommend grepping for lib.*sgpp (case-insensitive) to find most of them.

Running "grep --exclude-dir=.vscode* --exclude=*.log -InHr lib.*sgpp ." at root did not yield any more useful results for me (asides from finding build scripts by Malte and Fabian that shouldn't be there in the first place).

Regarding the wiki: Yes that has to be skimmed as well. We will also have to send out an email notifying users of the new behavior.

**Comment by valentjn** [comment]
@leiterrl I stand corrected, I thought there would be more places.

**Pull request merged**
