### PR TITLE
Configuration variables

### PR DESCRIPTION
**Pull request by aafdarweesh**
Updating the names of variables and instances of Configurations to be standard across the project. 
ex. Configuration variables end with "_"
ex. instances end with "Config"

### CODE REVIEW

**Comment by valentjn** [comment]
Has the output folder accidentally been pushed? If yes, force-pushing its removal (i.e., not just commit & push) would help not unnecessarily increasing the size of the repo.

**Comment by aafdarweesh** [comment]
> Has the output folder accidentally been pushed? If yes, force-pushing its removal (i.e., not just commit & push) would help not unnecessarily increasing the size of the repo.

Updated

**Comment by spc90** [comment]
@leiterrl Any ideas what could cause that internal error of gcc in the Jenkins build?

**Comment by leiterrl** [comment]
> @leiterrl Any ideas what could cause that internal error of gcc in the Jenkins build?

Hm... probably a compiler bug which suggests that we should upgrade the gcc versions (currently gcc5) on our build servers. This happened before on the windows builds but not on linux. I'll see what I can do.

**Pull request merged**
