### PR TITLE
Base for Clustering Implementation. Visualization Fix

### PR DESCRIPTION
**Pull request by Vince505**
A visualization bug has been fixed. Now the module runs while using the Universal Miner.

The base structure for the new clustering models has been set. Implementation still pending

@krsgpp

### CODE REVIEW

**Comment by krsgpp** [comment]
@Vince505 can you split the fix for the visualizer in the universal miner off into a separate PR? I would like to merge that fix quick.

**Comment by Vince505** [comment]
Clustering changes were reverted. Only the visualization fix is done

**Comment by krsgpp** [comment]
The changed files still show a lot of clustering changes :-)

**Comment by Vince505** [comment]
Revert is finally completed :)

**Pull request merged**
