### PR TITLE
Fix and auto-run examples

### LINKED ISSUE #101: Examples are not automatically executed
Currently, only unit tests are executed automatically. There should be an option to run the examples, too. Right now, they're compiled but not run. This leads to situations like #99 or #100 in which the examples become outdated. Examples that produce errors might scare new SG++ users.

A fix could be via additional SCons flags, e.g., `RUN_CPP_EXAMPLES=1`, disabled by default. There could be one flag for each language or just one for all enabled languages.

After fixing this, the flag should be enabled in the `.travis.yml` for the `medium` and the `full` Travis job.

### PR DESCRIPTION
**Pull request by valentjn**
Some of the C++ examples and many Python examples fail when run. IMO examples should
* work out-of-the-box without additional dependencies or command-line parameters,
* be quick to run, and
* be instructive and well-documented.

Missing dependencies should be detected by examples and example parts that need these dependencies should be skipped.

The lists below are already based on the fixes of #100 (see also #99). Tick the items that have been fixed.

This also contains #102: If the new SCons flags `RUN_CPP_EXAMPLES` or `RUN_PYTHON_EXAMPLES` are set, all C++ or Python examples are executed at the end of the SCons run. This PR also runs the examples in the Travis jobs. Fixes #101.

## C++ Examples
* [x] `base/examples/gridTExample.cpp`: fails without arguments
* [x] `combigrid/examples/bspline_pce.cpp`: fails without Eigen (@MichaelReh?)
* [x] `combigrid/examples/combigrid`: fails without Eigen or DAKOTA
* [x] `combigrid/examples/pce.cpp`: fails without Eigen or DAKOTA
* [x] `combigrid/examples/performance.cpp`: fails without Eigen or DAKOTA
  * **removed**
* [x] `combigrid/examples/sc.cpp`: fails without Eigen or DAKOTA
  * **removed**
* [x] `datadriven/examples/benchmark_OrthoAdapt.cpp`:fails because DBMatOfflineOrthoAdapt::decomposeMatrix is #ifdef'd out when compiling without GSL (@krsgpp?)
  * **removed**
* [x] `datadriven/examples/buildMats.cpp`: fails with GSL error
  * **removed**
* [x] `datadriven/examples/learnerSGDEOnlineTest.cpp`: segfaults because "validData" and "validLabels" are never initialized - remove?
  * **removed**
* [x] `datadriven/examples/learnerSGDETest.cpp`: fails due to missing data file - maybe switch to a different dataset
  * **removed**
* [x] `datadriven/examples/learnerSVMTest.cpp`: fails with DataVector exception - ultimately also caused by missing validation dataset but hidden by another bug (processedPoints in LearnerSVM::train is never incremented)
  * **removed**
* [x] `datadriven/examplesPipeline/ExampleDatabase.cpp`: fails without arguments
* [x] `datadriven/examplesPipeline/ExampleManualPipeline.cpp`: fails without arguments
  * **removed**
* [x] `datadriven/examplesPipeline/HPOMiner.cpp`: fails without arguments
* [x] `datadriven/examplesPipeline/ParallelMiner.cpp`: fails without arguments, needs ScaLAPACK
  * **removed**
* [x] `datadriven/examplesPipeline/UniversalMiner.cpp`: fails without arguments
  * **removed**
* [x] `optimization/examples/constrainedOptimization.cpp`: freezes/takes too long (@valentjn)

## Python Examples
* [x] `base/examples/gridTExample.py`: fails without arguments
* [x] `base/examples/predictiveANOVARefinement.py`: fails without Matplotlib
* [x] `base/examples/predictiveRefinement.py`: fails without Matplotlib
* [x] `base/examples/subspaceRefinement.py`: fails without Matplotlib
* [x] `combigrid/examples/bSplines.py`: fails without Matplotlib
* [x] `combigrid/examples/convergence.py`: fails without Matplotlib
* [x] `combigrid/examples/example_comparison.py`: fails without Matplotlib
* [x] `combigrid/examples/gettingStarted.py`: fails without Matplotlib
* [x] `combigrid/examples/gridConverter.py`: fails without Matplotlib
* [x] `combigrid/examples/plot_2d_sparse_grids.py`: fails without Matplotlib
* [x] `combigrid/examples/point_distributions.py`: fails without Matplotlib
* [x] `datadriven/examples/diagonalRegularizationExample.py`: fails without requests, broken due to sklearn API change
  * **removed**
* [x] `datadriven/examples/generalisedGridsTest.py`: fails without sklearn
* [x] `datadriven/examples/interactionExample.py`: fails without Pandas, broken (invalid arguments passed to DataVector constructor)
  * **removed**
* [x] `datadriven/examples/learnerExample.py`: fails without Matplotlib
* [x] `datadriven/examples/learnerSGDETest.py`: fails without sklearn
* [x] `datadriven/examples/positive_density.py`: fails without Matplotlib
* [x] `datadriven/examples/sparsePathExample.py`: fails without arguments, fails without Pandas, broken: segfaults
  * **removed**
* [x] `datadriven/examples/test_Rosenblatt.py`: fails without Matplotlib
* [x] `datadriven/examples/test_sgdeLaplace.py`: fails without Matplotlib, broken
  * **removed**
* [x] `misc/examples/resumeLearningProcess.py`: fails due to missing data file
  * **removed**
* [x] `pde/examples/LTwoDotTest.py`: fails without Matplotlib

### CODE REVIEW

**Comment by spc90** [comment]
So, I have some things to add and argue about with your list or requirements @valentjn :

> - work out-of-the-box without additional dependencies or command-line parameters

Examples should show functionality, and some of that functionality only works for certain dependencies and using command line arguments (e.g. using JSON files is the whole deal of the DM pipeline configuration!). I suggest instead, as we move to automate all examples, to have these examples also guarded by the same macros the corresponding inner code works with (e.g. Eigen, GSL), as I am against either removing them or modifying them to eliminate everything that makes them showcase what the code does. And for the ones with command line params we need proper documentation, showing what params it expects and also which additional file paths are needed. This is foremost the job of whoever created the example (if still exists) or whoever knows how the example should run. I'm not sure how to automate command line params for certain examples though, but there has to be a way, right?

> - be quick to run

Agreed! I've discussed yesterday with @krsgpp  to maybe move to smaller datasets for the datadriven examples, instead of the bigger ones. Of course, if comparing running time or noops of different methods is the idea of a particular example, then probably this shouldn't change that much.

> - be instructive and well-documented.

Obviously! :smile: :+1:

**Comment by valentjn** [comment]
@spc90 Re the first point, I fully agree. The macro thing is what I meant with skipping example parts. A lot of the Python examples are simply fixed by checking for `ModuleNotFoundError`s. I'm also against removing in general; examples should output that a part of the (or the whole) example needs dependency X, but it should exit with code 0 such that the automated execution doesn't fail. Only if an example e.g. segfaults and we're not able to fix that without too much effort, I'd opt for removing stuff. It'll still be in the Git history if people fix it.

Most of the CLI arguments stuff is already fixed (ticked items in the list) simply by using reasonable default values for missing arguments.

Oh, and there might be more issues as the ones listed for each example. It's just the first errors that come up---maybe there's other problems if we fix them.

**Comment by krsgpp** [comment]
commit b85ca6f9bf1cd446e4d6bf89d3d4e6db4e0ea3db removes examples vital to the datamining pipeline.

All changes done in the commit from the examplesPipeline Folder needs to be reverted.

Also, please request my review next time you change (or delete!) stuff in examplesPipeline or the src/datamining folder.

**Comment by valentjn** [comment]
Removed examples may be re-added by a new PR as in #160. Travis automatically tests the examples now as all examples should run without errors in the next release.

As discussed above, examples should just showcase the functionality. Reasonable defaults for configuration files/command-line arguments are IMO part of examples, as otherwise it won't be clear for new users how to use the code. Vital application code, as opposed to showcase examples, should be stored separately (e.g., external repos).

**Pull request merged**
