### PR TITLE
Pipeline default value improvement

### PR DESCRIPTION
**Pull request by elfeck**
This PR improves how and where the default values for pipeline-configuration are set. This is part of the old gitlab MR90 (datamining pipeline documentation).

@krsgpp

### CODE REVIEW

**Comment by krsgpp** [comment]
@elfeck Travis tests fail.

I think the problem is related to:

> # Did not find densityEstimationConfig[matrixDecompositionType]. Setting default value LU.

This should default to Chol, right? At least that is what I see in the code.

**Comment by elfeck** [comment]
Yes, thanks. I will fix the test and make sure all succeed on my machine

**Comment by elfeck** [comment]
So this has been keeping me busy for a while now with no direct fix yet. I was able to fix the tests by explicitly setting the value for `matrixDecompositionType` to `chol` but the default value should be `chol` anyway as per [here](https://github.com/elfeck/SGpp/blob/pipeline_default_improv/datadriven/src/sgpp/datadriven/datamining/modules/fitting/FitterConfiguration.cpp#L139).

So this is pointing out that the default-values are not necessarily assigned in time, which is definitely something which should be investigated and fixed before merge.

My guess is that this default-setting function is not called in time for some reason and the default is taken from somewhere else which apparently sets `LU`. [The struct](https://github.com/elfeck/SGpp/blob/pipeline_default_improv/datadriven/src/sgpp/datadriven/datamining/modules/fitting/FitterConfiguration.cpp#L139) for this config does not initialize at all so this might be an undefined-behavior `0` which corresponds to `LU`.

**Comment by elfeck** [comment]
The problem were missing function calls to the parent class `FitterConfiguration` that now sets up all default values. Test succeed locally now.

**Comment by elfeck** [comment]
I fixed all obvious lint warnings. If someone could start the tests for me, that would be great.

**Pull request merged**
