### PR TITLE
OSX/Python: Use only -undefined dynamic_lookup

### PR DESCRIPTION
**Pull request by jschueller**
-lpython is unneeded and may cause link error if the python lib is not provided
-flat_namespace seems unneeded

### CODE REVIEW

**Comment by valentjn** [comment]
Thank you for all these helpful fixes. How many PRs are you going to open? Each PR has to be tested with CI and takes 1-2h minimum. You don't have to open separate PRs for each small thing you change. That would also be better for my inbox ;)

**Comment by jschueller** [comment]
I think this is it :)

**Comment by pfluegdk** [comment]
We're definitely happy about all and many PRs! No objections at all! :-)
As I currently don't have an OSX system to test on: Am I right to assume that you did successfully create the python libs? In the past, we needed the -flat_namespace to create the same lib pysgpp as on Windows and Linux.

**Comment by jschueller** [comment]
Yes, this works for Linux & OSX: see https://github.com/conda-forge/sgpp-feedstock

**Pull request merged**
