### PR TITLE
Scons: pick up flags from env

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by valentjn** [comment]
There are already the CPPFLAGS and the LINKFLAGS SCons parameters (e.g., `scons CPPFLAGS=-Wall`), there should no need for this.

**Comment by jschueller** [comment]
May I argue that you cannot pass linker flags containing commas "-Wl,-rpath", this is a big limitation: you cannot pass rpaths or anything

**Comment by valentjn** [comment]
This is indeed an issue. But this PR just adds another possibility to supply options and splits by space characters. Then we have two different possibilities with different splittings. It would be difficult to remember which splits how. And what happens if options contain both spaces and commas?

Can we modify the existing mechanism by somehow allowing to escape commas, for instance with a double comma? The problem also applies to other SCons options (`SWIGFLAGS` etc.).

**Comment by jschueller** [comment]
First let me say that it is standard for build system to pick up environment variables (autotools, cmake, ...), as often package builders (debian, rpm, ...) set a bunch of standard flags in the environment, it would be a pain to have to split them by spaces, then feed them via a list with the right separator.

**Comment by jschueller** [comment]
Hello @valentjn can you please reconsider ?

**Comment by jschueller** [comment]
@valentjn @pfluegdk @leiterrl 
Please reconsider, this is the only way I could pass the numerous c & link flags (with commas) 
for https://github.com/conda-forge/sgpp-feedstock

**Comment by valentjn** [comment]
It seems there is no easy way to get around the escaping problem. Proposal: Change the existing mechanism to split by spaces instead of commas, as that seems the standard in other software. It might cause problems with paths that contain spaces, but that's still better than not supporting linker flags.

@jschueller Would you be happy with that, i.e., `scons LINKFLAGS=-Wl,-rpath`, or do you really need setting it by environment variables?

**Comment by jschueller** [comment]
I guess splitting by spaces would be ok too

**Comment by valentjn** [comment]
Splitting is now by spaces via #159.

**Pull request closed without merging**
